
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: sda-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: sda
      RABBITMQ_DEFAULT_PASS: sda123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

  postgres:
    image: postgres:15
    container_name: sda-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: atos123
      POSTGRES_DB: sda_dev_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  api:
    build: ./backend
    container_name: sda-api
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - postgres
    env_file:
      - ./backend/.env
    environment:
      DOCKER_ENV: "true"
      DB_HOST: postgres

  worker:
    build: ./backend
    container_name: sda-worker
    command: python worker.py
    env_file:
      - ./backend/.env
    environment:
      DOCKER_ENV: "true"
    depends_on:
      - postgres
      - rabbitmq

volumes:
  rabbitmq_data:
  postgres_data: