version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: sda-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: sda
      RABBITMQ_DEFAULT_PASS: sda123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

volumes:
  rabbitmq_data: